import type { QuizDefinition } from './QuizDefinition';

/**
 * Static registry of all available quizzes.
 * Each entry is a complete QuizDefinition with metadata and data paths.
 * The navigation tree is built from these definitions' path segments.
 *
 * Add new quizzes here. Order determines display order within categories.
 */

/**
 * Shared configuration for all capitals quizzes.
 * Individual definitions spread this and add id, title, description, and dataFilter.
 */
const capitalsQuizBase = {
  path: ['Geography', 'Capitals'] as const,
  visualizationType: 'map' as const,
  availableModes: ['free-recall-unordered', 'identify', 'locate'] as const,
  defaultMode: 'free-recall-unordered' as const,
  toggles: [
    { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' } as const,
    { key: 'showCityDots', label: 'City dots', defaultValue: true, group: 'display', hiddenBehavior: 'on-reveal' } as const,
    { key: 'showCountryNames', label: 'Country names on map', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' } as const,
    { key: 'showMapFlags', label: 'Flags on map', defaultValue: false, group: 'display', hiddenBehavior: { hintAfter: 2 } } as const,
    { key: 'showPromptCountryNames', label: 'Country names in prompt', defaultValue: false, group: 'display', hiddenBehavior: 'never', promptField: { type: 'text', column: 'country' }, modes: ['identify'] } as const,
    { key: 'showPromptFlags', label: 'Flags in prompt', defaultValue: false, group: 'display', hiddenBehavior: 'never', promptField: { type: 'flag', column: 'code' }, modes: ['identify'] } as const,
  ],
  presets: [
    {
      name: 'easy',
      label: 'Easy',
      values: { showBorders: true, showCityDots: true, showCountryNames: true, showMapFlags: true, showPromptCountryNames: true, showPromptFlags: true },
    },
    {
      name: 'medium',
      label: 'Medium',
      values: { showBorders: true, showCityDots: true, showCountryNames: false, showMapFlags: false, showPromptCountryNames: false, showPromptFlags: false },
    },
    {
      name: 'hard',
      label: 'Hard',
      values: { showBorders: false, showCityDots: false, showCountryNames: false, showMapFlags: false, showPromptCountryNames: false, showPromptFlags: false },
    },
  ],
  columnMappings: {
    answer: 'city',
    label: 'city',
    latitude: 'latitude',
    longitude: 'longitude',
    group: 'country',
    code: 'country_code',
  },
  dataPath: '/data/capitals/world-capitals.csv',
  supportingDataPaths: ['/data/borders/world-borders.csv'],
  modeConstraints: {
    identify: [
      { type: 'forced' as const, key: 'showCityDots', forcedValue: true, reason: 'City dots are required for clicking in identify mode' },
      { type: 'atLeastOne' as const, keys: ['showPromptCountryNames', 'showPromptFlags'], reason: 'At least one hint must be enabled in identify mode' },
    ],
  },
} satisfies Omit<QuizDefinition, 'id' | 'title' | 'description'>;

export const quizRegistry: ReadonlyArray<QuizDefinition> = [
  {
    ...capitalsQuizBase,
    id: 'geo-capitals-europe',
    title: 'European Capitals',
    description: 'Name the capital cities of European countries.',
    dataFilter: { column: 'region', values: ['Europe'] },
  },
  {
    ...capitalsQuizBase,
    id: 'geo-capitals-asia',
    title: 'Asian Capitals',
    description: 'Name the capital cities of Asian countries.',
    dataFilter: { column: 'region', values: ['Asia'] },
  },
  {
    ...capitalsQuizBase,
    id: 'geo-capitals-africa',
    title: 'African Capitals',
    description: 'Name the capital cities of African countries.',
    dataFilter: { column: 'region', values: ['Africa'] },
  },
  {
    ...capitalsQuizBase,
    id: 'geo-capitals-north-america',
    title: 'North American Capitals',
    description: 'Name the capital cities of North America, Central America, and the Caribbean.',
    dataFilter: { column: 'subregion', values: ['North America', 'Central America', 'Caribbean'] },
    initialViewBox: { x: -130, y: -50, width: 72, height: 43 },
  },
  {
    ...capitalsQuizBase,
    id: 'geo-capitals-south-america',
    title: 'South American Capitals',
    description: 'Name the capital cities of South American countries.',
    dataFilter: { column: 'subregion', values: ['South America'] },
    initialViewBox: { x: -85, y: -15, width: 55, height: 73 },
  },
  {
    ...capitalsQuizBase,
    id: 'geo-capitals-oceania',
    title: 'Oceanian Capitals',
    description: 'Name the capital cities of Oceanian countries.',
    dataFilter: { column: 'region', values: ['Oceania'] },
  },
  {
    ...capitalsQuizBase,
    id: 'geo-capitals-world',
    title: 'World Capitals',
    description: 'Name all 197 capital cities of the world.',
    initialViewBox: { x: -169, y: -70, width: 360, height: 130 },
  },
  {
    id: 'geo-countries-europe',
    title: 'European Countries',
    description: 'Identify the countries of Europe on a map.',
    path: ['Geography', 'Countries'],
    visualizationType: 'map',
    availableModes: ['free-recall-unordered', 'identify'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
      { key: 'showMapFlags', label: 'Flags on map', defaultValue: false, group: 'display', hiddenBehavior: { hintAfter: 2 } },
    ],
    presets: [],
    columnMappings: {
      answer: 'country',
      label: 'country',
      group: 'region',
    },
    dataPath: '/data/geography/countries/europe.csv',
    supportingDataPaths: ['/data/borders/world-borders.csv'],
  },
  {
    id: 'geo-countries-asia',
    title: 'Asian Countries',
    description: 'Identify the countries of Asia on a map.',
    path: ['Geography', 'Countries'],
    visualizationType: 'map',
    availableModes: ['free-recall-unordered', 'identify'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
    ],
    presets: [],
    columnMappings: {
      answer: 'country',
      label: 'country',
      group: 'region',
    },
    dataPath: '/data/geography/countries/asia.csv',
    supportingDataPaths: ['/data/borders/world-borders.csv'],
  },
  {
    id: 'geo-flags-europe',
    title: 'European Flags',
    description: 'Match European countries to their flags.',
    path: ['Geography', 'Flags'],
    visualizationType: 'flag-grid',
    availableModes: ['free-recall-unordered', 'multiple-choice', 'prompted-recall'],
    defaultMode: 'multiple-choice',
    toggles: [
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
    ],
    presets: [],
    columnMappings: {
      answer: 'country',
      label: 'country',
      flag: 'country_code',
      group: 'subregion',
    },
    dataPath: '/data/capitals/world-capitals.csv',
    dataFilter: { column: 'region', values: ['Europe'] },
    supportingDataPaths: [],
  },
  {
    id: 'geo-flags-asia',
    title: 'Asian Flags',
    description: 'Match Asian countries to their flags.',
    path: ['Geography', 'Flags'],
    visualizationType: 'flag-grid',
    availableModes: ['free-recall-unordered', 'multiple-choice', 'prompted-recall'],
    defaultMode: 'multiple-choice',
    toggles: [
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
    ],
    presets: [],
    columnMappings: {
      answer: 'country',
      label: 'country',
      flag: 'country_code',
      group: 'subregion',
    },
    dataPath: '/data/capitals/world-capitals.csv',
    dataFilter: { column: 'region', values: ['Asia'] },
    supportingDataPaths: [],
  },
  {
    id: 'geo-flags-africa',
    title: 'African Flags',
    description: 'Match African countries to their flags.',
    path: ['Geography', 'Flags'],
    visualizationType: 'flag-grid',
    availableModes: ['free-recall-unordered', 'multiple-choice', 'prompted-recall'],
    defaultMode: 'multiple-choice',
    toggles: [
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
    ],
    presets: [],
    columnMappings: {
      answer: 'country',
      label: 'country',
      flag: 'country_code',
      group: 'subregion',
    },
    dataPath: '/data/capitals/world-capitals.csv',
    dataFilter: { column: 'region', values: ['Africa'] },
    supportingDataPaths: [],
  },
  {
    id: 'geo-flags-americas',
    title: 'Americas Flags',
    description: 'Match countries of the Americas to their flags.',
    path: ['Geography', 'Flags'],
    visualizationType: 'flag-grid',
    availableModes: ['free-recall-unordered', 'multiple-choice', 'prompted-recall'],
    defaultMode: 'multiple-choice',
    toggles: [
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
    ],
    presets: [],
    columnMappings: {
      answer: 'country',
      label: 'country',
      flag: 'country_code',
      group: 'subregion',
    },
    dataPath: '/data/capitals/world-capitals.csv',
    dataFilter: { column: 'region', values: ['Americas'] },
    supportingDataPaths: [],
  },
  {
    id: 'geo-flags-oceania',
    title: 'Oceania Flags',
    description: 'Match Oceanian countries to their flags.',
    path: ['Geography', 'Flags'],
    visualizationType: 'flag-grid',
    availableModes: ['free-recall-unordered', 'multiple-choice', 'prompted-recall'],
    defaultMode: 'multiple-choice',
    toggles: [
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
    ],
    presets: [],
    columnMappings: {
      answer: 'country',
      label: 'country',
      flag: 'country_code',
      group: 'subregion',
    },
    dataPath: '/data/capitals/world-capitals.csv',
    dataFilter: { column: 'region', values: ['Oceania'] },
    supportingDataPaths: [],
  },
  {
    id: 'geo-flags-world',
    title: 'World Flags',
    description: 'Match all countries of the world to their flags.',
    path: ['Geography', 'Flags'],
    visualizationType: 'flag-grid',
    availableModes: ['free-recall-unordered', 'multiple-choice', 'prompted-recall'],
    defaultMode: 'multiple-choice',
    toggles: [
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
    ],
    presets: [],
    columnMappings: {
      answer: 'country',
      label: 'country',
      flag: 'country_code',
      group: 'subregion',
    },
    dataPath: '/data/capitals/world-capitals.csv',
    supportingDataPaths: [],
  },
  {
    id: 'sci-periodic-table',
    title: 'Periodic Table',
    description: 'Name the elements of the periodic table.',
    path: ['Science', 'Chemistry', 'Periodic Table'],
    visualizationType: 'grid',
    availableModes: ['free-recall-unordered', 'prompted-recall', 'free-recall-ordered', 'identify'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showSymbols', label: 'Element symbols', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showAtomicNumbers', label: 'Atomic numbers', defaultValue: true, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showNames', label: 'Element names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showGroups', label: 'Category colours', defaultValue: false, group: 'display', hiddenBehavior: 'never' },
    ],
    presets: [
      {
        name: 'easy',
        label: 'Easy',
        values: { showSymbols: true, showAtomicNumbers: true, showNames: false, showGroups: true },
      },
      {
        name: 'hard',
        label: 'Hard',
        values: { showSymbols: false, showAtomicNumbers: false, showNames: false, showGroups: false },
      },
    ],
    columnMappings: {
      answer: 'name',
      label: 'name',
      group: 'category',
    },
    dataPath: '/data/science/chemistry/periodic-table.csv',
    supportingDataPaths: [],
    rangeColumn: 'atomic_number',
    rangeLabel: 'Atomic number',
  },
  {
    id: 'sci-human-bones',
    title: 'Human Bones',
    description: 'Name the bones of the human skeleton.',
    path: ['Science', 'Biology', 'Human Bones'],
    visualizationType: 'grid',
    availableModes: ['free-recall-unordered', 'identify'],
    defaultMode: 'free-recall-unordered',
    toggles: [],
    presets: [],
    columnMappings: {
      answer: 'bone',
      label: 'bone',
      group: 'region',
    },
    dataPath: '/data/science/biology/human-bones.csv',
    supportingDataPaths: [],
  },
  {
    id: 'hist-emperors-roman',
    title: 'Roman Emperors',
    description: 'Name the emperors of Rome in chronological order.',
    path: ['History', 'Ancient', 'Roman Emperors'],
    visualizationType: 'timeline',
    availableModes: ['free-recall-unordered'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showDates', label: 'Reign dates', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showDynasty', label: 'Dynasty colours', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
    ],
    presets: [],
    columnMappings: {
      answer: 'emperor',
      label: 'emperor',
      group: 'dynasty',
    },
    dataPath: '/data/history/ancient/roman-emperors.csv',
    supportingDataPaths: [],
  },
  {
    id: 'hist-timeline-ww2',
    title: 'World War II Timeline',
    description: 'Place key events of World War II on a timeline.',
    path: ['History', 'Modern', 'World War II Timeline'],
    visualizationType: 'timeline',
    availableModes: ['free-recall-unordered', 'identify', 'locate'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showDates', label: 'Event dates', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showTheatreColours', label: 'Theatre colours', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
    ],
    selectToggles: [
      {
        key: 'datePrecision',
        label: 'Date precision',
        options: [
          { value: 'year', label: 'Year' },
          { value: 'month', label: 'Month' },
          { value: 'day', label: 'Day' },
        ],
        defaultValue: 'month',
        group: 'display',
        modes: ['locate'],
      },
    ],
    presets: [
      {
        name: 'easy',
        label: 'Easy',
        values: { showDates: true, showTheatreColours: true },
      },
      {
        name: 'hard',
        label: 'Hard',
        values: { showDates: false, showTheatreColours: false },
      },
    ],
    columnMappings: {
      answer: 'event',
      label: 'event',
      group: 'theatre',
    },
    dataPath: '/data/history/modern/ww2-timeline.csv',
    supportingDataPaths: [],
  },
];
