import type { QuizDefinition } from './QuizDefinition';

/**
 * Static registry of all available quizzes.
 * Each entry is a complete QuizDefinition with metadata and data paths.
 * The navigation tree is built from these definitions' path segments.
 *
 * Add new quizzes here. Order determines display order within categories.
 */
export const quizRegistry: ReadonlyArray<QuizDefinition> = [
  {
    id: 'geo-capitals-europe',
    title: 'European Capitals',
    description: 'Name the capital cities of European countries.',
    path: ['Geography', 'Capitals'],
    visualizationType: 'map',
    availableModes: ['free-recall-unordered', 'identify', 'locate'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
      { key: 'showCityDots', label: 'City dots', defaultValue: true, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showCountryNames', label: 'Country names on map', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showMapFlags', label: 'Flags on map', defaultValue: false, group: 'display', hiddenBehavior: { hintAfter: 2 } },
      { key: 'showPromptCountryNames', label: 'Country names in prompt', defaultValue: false, group: 'display', hiddenBehavior: 'never', promptField: { type: 'text', column: 'country' }, modes: ['identify'] },
      { key: 'showPromptFlags', label: 'Flags in prompt', defaultValue: false, group: 'display', hiddenBehavior: 'never', promptField: { type: 'flag', column: 'code' }, modes: ['identify'] },
    ],
    presets: [
      {
        name: 'easy',
        label: 'Easy',
        values: { showBorders: true, showCityDots: true, showCountryNames: true, showMapFlags: true, showPromptCountryNames: true, showPromptFlags: true },
      },
      {
        name: 'medium',
        label: 'Medium',
        values: { showBorders: true, showCityDots: true, showCountryNames: false, showMapFlags: false, showPromptCountryNames: false, showPromptFlags: false },
      },
      {
        name: 'hard',
        label: 'Hard',
        values: { showBorders: false, showCityDots: false, showCountryNames: false, showMapFlags: false, showPromptCountryNames: false, showPromptFlags: false },
      },
    ],
    columnMappings: {
      answer: 'city',
      label: 'city',
      latitude: 'latitude',
      longitude: 'longitude',
      group: 'country',
      code: 'code',
    },
    dataPath: '/data/capitals/world-capitals.csv',
    dataFilter: { column: 'region', values: ['Europe'] },
    supportingDataPaths: ['/data/borders/world-borders.csv'],
    modeConstraints: {
      identify: [
        { type: 'forced', key: 'showCityDots', forcedValue: true, reason: 'City dots are required for clicking in identify mode' },
        { type: 'atLeastOne', keys: ['showPromptCountryNames', 'showPromptFlags'], reason: 'At least one hint must be enabled in identify mode' },
      ],
    },
  },
  {
    id: 'geo-capitals-asia',
    title: 'Asian Capitals',
    description: 'Name the capital cities of Asian countries.',
    path: ['Geography', 'Capitals'],
    visualizationType: 'map',
    availableModes: ['free-recall-unordered', 'identify', 'locate'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
      { key: 'showCityDots', label: 'City dots', defaultValue: true, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
    ],
    presets: [
      {
        name: 'easy',
        label: 'Easy',
        values: { showBorders: true, showCityDots: true, showCountryNames: true },
      },
      {
        name: 'hard',
        label: 'Hard',
        values: { showBorders: false, showCityDots: false, showCountryNames: false },
      },
    ],
    columnMappings: {
      answer: 'city',
      label: 'city',
      latitude: 'latitude',
      longitude: 'longitude',
      group: 'country',
      code: 'code',
    },
    dataPath: '/data/capitals/world-capitals.csv',
    dataFilter: { column: 'region', values: ['Asia'] },
    supportingDataPaths: ['/data/borders/world-borders.csv'],
  },
  {
    id: 'geo-capitals-africa',
    title: 'African Capitals',
    description: 'Name the capital cities of African countries.',
    path: ['Geography', 'Capitals'],
    visualizationType: 'map',
    availableModes: ['free-recall-unordered', 'identify', 'locate'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
      { key: 'showCityDots', label: 'City dots', defaultValue: true, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
    ],
    presets: [
      {
        name: 'easy',
        label: 'Easy',
        values: { showBorders: true, showCityDots: true, showCountryNames: true },
      },
      {
        name: 'hard',
        label: 'Hard',
        values: { showBorders: false, showCityDots: false, showCountryNames: false },
      },
    ],
    columnMappings: {
      answer: 'city',
      label: 'city',
      latitude: 'latitude',
      longitude: 'longitude',
      group: 'country',
      code: 'code',
    },
    dataPath: '/data/capitals/world-capitals.csv',
    dataFilter: { column: 'region', values: ['Africa'] },
    supportingDataPaths: ['/data/borders/world-borders.csv'],
  },
  {
    id: 'geo-countries-europe',
    title: 'European Countries',
    description: 'Identify the countries of Europe on a map.',
    path: ['Geography', 'Countries'],
    visualizationType: 'map',
    availableModes: ['free-recall-unordered', 'identify'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
      { key: 'showMapFlags', label: 'Flags on map', defaultValue: false, group: 'display', hiddenBehavior: { hintAfter: 2 } },
    ],
    presets: [],
    columnMappings: {
      answer: 'country',
      label: 'country',
      group: 'region',
    },
    dataPath: '/data/geography/countries/europe.csv',
    supportingDataPaths: ['/data/borders/world-borders.csv'],
  },
  {
    id: 'geo-countries-asia',
    title: 'Asian Countries',
    description: 'Identify the countries of Asia on a map.',
    path: ['Geography', 'Countries'],
    visualizationType: 'map',
    availableModes: ['free-recall-unordered', 'identify'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
    ],
    presets: [],
    columnMappings: {
      answer: 'country',
      label: 'country',
      group: 'region',
    },
    dataPath: '/data/geography/countries/asia.csv',
    supportingDataPaths: ['/data/borders/world-borders.csv'],
  },
  {
    id: 'geo-flags-europe',
    title: 'European Flags',
    description: 'Match European countries to their flags.',
    path: ['Geography', 'Flags'],
    visualizationType: 'grid',
    availableModes: ['identify', 'free-recall-unordered'],
    defaultMode: 'identify',
    toggles: [
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
    ],
    presets: [],
    columnMappings: {
      answer: 'country',
      label: 'country',
      group: 'region',
    },
    dataPath: '/data/geography/flags/europe.csv',
    supportingDataPaths: [],
  },
  {
    id: 'sci-periodic-table',
    title: 'Periodic Table',
    description: 'Name the elements of the periodic table.',
    path: ['Science', 'Chemistry', 'Periodic Table'],
    visualizationType: 'grid',
    availableModes: ['free-recall-unordered', 'prompted-recall', 'free-recall-ordered', 'identify'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showSymbols', label: 'Element symbols', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showAtomicNumbers', label: 'Atomic numbers', defaultValue: true, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showNames', label: 'Element names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showGroups', label: 'Category colours', defaultValue: false, group: 'display', hiddenBehavior: 'never' },
    ],
    presets: [
      {
        name: 'easy',
        label: 'Easy',
        values: { showSymbols: true, showAtomicNumbers: true, showNames: false, showGroups: true },
      },
      {
        name: 'hard',
        label: 'Hard',
        values: { showSymbols: false, showAtomicNumbers: false, showNames: false, showGroups: false },
      },
    ],
    columnMappings: {
      answer: 'name',
      label: 'name',
      group: 'category',
    },
    dataPath: '/data/science/chemistry/periodic-table.csv',
    supportingDataPaths: [],
    rangeColumn: 'atomic_number',
    rangeLabel: 'Atomic number',
  },
  {
    id: 'sci-human-bones',
    title: 'Human Bones',
    description: 'Name the bones of the human skeleton.',
    path: ['Science', 'Biology', 'Human Bones'],
    visualizationType: 'grid',
    availableModes: ['free-recall-unordered', 'identify'],
    defaultMode: 'free-recall-unordered',
    toggles: [],
    presets: [],
    columnMappings: {
      answer: 'bone',
      label: 'bone',
      group: 'region',
    },
    dataPath: '/data/science/biology/human-bones.csv',
    supportingDataPaths: [],
  },
  {
    id: 'hist-emperors-roman',
    title: 'Roman Emperors',
    description: 'Name the emperors of Rome in chronological order.',
    path: ['History', 'Ancient', 'Roman Emperors'],
    visualizationType: 'timeline',
    availableModes: ['free-recall-unordered'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showDates', label: 'Reign dates', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showDynasty', label: 'Dynasty colours', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
    ],
    presets: [],
    columnMappings: {
      answer: 'emperor',
      label: 'emperor',
      group: 'dynasty',
    },
    dataPath: '/data/history/ancient/roman-emperors.csv',
    supportingDataPaths: [],
  },
  {
    id: 'hist-timeline-ww2',
    title: 'World War II Timeline',
    description: 'Place key events of World War II on a timeline.',
    path: ['History', 'Modern', 'World War II Timeline'],
    visualizationType: 'timeline',
    availableModes: ['free-recall-unordered', 'locate'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showDates', label: 'Event dates', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
    ],
    presets: [],
    columnMappings: {
      answer: 'event',
      label: 'event',
      group: 'theatre',
    },
    dataPath: '/data/history/modern/ww2-timeline.csv',
    supportingDataPaths: [],
  },
];
