import type { QuizDefinition } from './QuizDefinition';

/**
 * Static registry of all available quizzes.
 * Each entry is a complete QuizDefinition with metadata and data paths.
 * The navigation tree is built from these definitions' path segments.
 *
 * Add new quizzes here. Order determines display order within categories.
 */
export const quizRegistry: ReadonlyArray<QuizDefinition> = [
  {
    id: 'geo-capitals-europe',
    title: 'European Capitals',
    description: 'Name the capital cities of European countries.',
    path: ['Geography', 'Capitals'],
    visualizationType: 'map',
    availableModes: ['free-recall-unordered', 'identify', 'locate'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
      { key: 'showCityDots', label: 'City dots', defaultValue: true, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showFlags', label: 'Flags', defaultValue: false, group: 'display', hiddenBehavior: { hintAfter: 2 } },
    ],
    presets: [
      {
        name: 'easy',
        label: 'Easy',
        values: { showBorders: true, showCityDots: true, showCountryNames: true, showFlags: true },
      },
      {
        name: 'medium',
        label: 'Medium',
        values: { showBorders: true, showCityDots: true, showCountryNames: false, showFlags: false },
      },
      {
        name: 'hard',
        label: 'Hard',
        values: { showBorders: false, showCityDots: false, showCountryNames: false, showFlags: false },
      },
    ],
    columnMappings: {
      answer: 'city',
      label: 'city',
      latitude: 'latitude',
      longitude: 'longitude',
      group: 'country',
    },
    dataPath: '/data/capitals/world-capitals.csv',
    dataFilter: { column: 'region', values: ['Europe'] },
    supportingDataPaths: ['/data/borders/world-borders.csv'],
  },
  {
    id: 'geo-capitals-asia',
    title: 'Asian Capitals',
    description: 'Name the capital cities of Asian countries.',
    path: ['Geography', 'Capitals'],
    visualizationType: 'map',
    availableModes: ['free-recall-unordered', 'identify', 'locate'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
      { key: 'showCityDots', label: 'City dots', defaultValue: true, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
    ],
    presets: [
      {
        name: 'easy',
        label: 'Easy',
        values: { showBorders: true, showCityDots: true, showCountryNames: true },
      },
      {
        name: 'hard',
        label: 'Hard',
        values: { showBorders: false, showCityDots: false, showCountryNames: false },
      },
    ],
    columnMappings: {
      answer: 'city',
      label: 'city',
      latitude: 'latitude',
      longitude: 'longitude',
      group: 'country',
    },
    dataPath: '/data/capitals/world-capitals.csv',
    dataFilter: { column: 'region', values: ['Asia'] },
    supportingDataPaths: ['/data/borders/world-borders.csv'],
  },
  {
    id: 'geo-capitals-africa',
    title: 'African Capitals',
    description: 'Name the capital cities of African countries.',
    path: ['Geography', 'Capitals'],
    visualizationType: 'map',
    availableModes: ['free-recall-unordered', 'identify', 'locate'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
      { key: 'showCityDots', label: 'City dots', defaultValue: true, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
    ],
    presets: [
      {
        name: 'easy',
        label: 'Easy',
        values: { showBorders: true, showCityDots: true, showCountryNames: true },
      },
      {
        name: 'hard',
        label: 'Hard',
        values: { showBorders: false, showCityDots: false, showCountryNames: false },
      },
    ],
    columnMappings: {
      answer: 'city',
      label: 'city',
      latitude: 'latitude',
      longitude: 'longitude',
      group: 'country',
    },
    dataPath: '/data/capitals/world-capitals.csv',
    dataFilter: { column: 'region', values: ['Africa'] },
    supportingDataPaths: ['/data/borders/world-borders.csv'],
  },
  {
    id: 'geo-countries-europe',
    title: 'European Countries',
    description: 'Name the countries of Europe from their shape on the map.',
    path: ['Geography', 'Countries'],
    visualizationType: 'map',
    initialViewBox: { x: -25, y: -72, width: 70, height: 37 },
    availableModes: ['free-recall-unordered', 'identify', 'locate', 'prompted-recall'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showFlags', label: 'Flags', defaultValue: false, group: 'display', hiddenBehavior: { hintAfter: 2 } },
    ],
    presets: [
      { name: 'easy', label: 'Easy', values: { showBorders: true, showCountryNames: true, showFlags: true } },
      { name: 'medium', label: 'Medium', values: { showBorders: true, showCountryNames: false, showFlags: false } },
      { name: 'hard', label: 'Hard', values: { showBorders: false, showCountryNames: false, showFlags: false } },
    ],
    columnMappings: {
      answer: 'name',
      label: 'name',
      latitude: 'latitude',
      longitude: 'longitude',
      group: 'group',
    },
    dataPath: '/data/borders/world-borders.csv',
    dataFilter: [
      { column: 'is_sovereign', values: ['true'] },
      { column: 'region', values: ['Europe'] },
    ],
    supportingDataPaths: ['/data/borders/world-borders.csv'],
  },
  {
    id: 'geo-countries-asia',
    title: 'Asian Countries',
    description: 'Name the countries of Asia from their shape on the map.',
    path: ['Geography', 'Countries'],
    visualizationType: 'map',
    initialViewBox: { x: 25, y: -55, width: 125, height: 65 },
    availableModes: ['free-recall-unordered', 'identify', 'locate', 'prompted-recall'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showFlags', label: 'Flags', defaultValue: false, group: 'display', hiddenBehavior: { hintAfter: 2 } },
    ],
    presets: [
      { name: 'easy', label: 'Easy', values: { showBorders: true, showCountryNames: true, showFlags: true } },
      { name: 'medium', label: 'Medium', values: { showBorders: true, showCountryNames: false, showFlags: false } },
      { name: 'hard', label: 'Hard', values: { showBorders: false, showCountryNames: false, showFlags: false } },
    ],
    columnMappings: {
      answer: 'name',
      label: 'name',
      latitude: 'latitude',
      longitude: 'longitude',
      group: 'group',
    },
    dataPath: '/data/borders/world-borders.csv',
    dataFilter: [
      { column: 'is_sovereign', values: ['true'] },
      { column: 'region', values: ['Asia'] },
    ],
    supportingDataPaths: ['/data/borders/world-borders.csv'],
  },
  {
    id: 'geo-countries-africa',
    title: 'African Countries',
    description: 'Name the countries of Africa from their shape on the map.',
    path: ['Geography', 'Countries'],
    visualizationType: 'map',
    initialViewBox: { x: -20, y: -38, width: 75, height: 73 },
    availableModes: ['free-recall-unordered', 'identify', 'locate', 'prompted-recall'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showFlags', label: 'Flags', defaultValue: false, group: 'display', hiddenBehavior: { hintAfter: 2 } },
    ],
    presets: [
      { name: 'easy', label: 'Easy', values: { showBorders: true, showCountryNames: true, showFlags: true } },
      { name: 'medium', label: 'Medium', values: { showBorders: true, showCountryNames: false, showFlags: false } },
      { name: 'hard', label: 'Hard', values: { showBorders: false, showCountryNames: false, showFlags: false } },
    ],
    columnMappings: {
      answer: 'name',
      label: 'name',
      latitude: 'latitude',
      longitude: 'longitude',
      group: 'group',
    },
    dataPath: '/data/borders/world-borders.csv',
    dataFilter: [
      { column: 'is_sovereign', values: ['true'] },
      { column: 'region', values: ['Africa'] },
    ],
    supportingDataPaths: ['/data/borders/world-borders.csv'],
  },
  {
    id: 'geo-countries-north-america',
    title: 'North American Countries',
    description: 'Name the countries of North America from their shape on the map.',
    path: ['Geography', 'Countries'],
    visualizationType: 'map',
    initialViewBox: { x: -170, y: -75, width: 120, height: 65 },
    availableModes: ['free-recall-unordered', 'identify', 'locate', 'prompted-recall'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showFlags', label: 'Flags', defaultValue: false, group: 'display', hiddenBehavior: { hintAfter: 2 } },
    ],
    presets: [
      { name: 'easy', label: 'Easy', values: { showBorders: true, showCountryNames: true, showFlags: true } },
      { name: 'medium', label: 'Medium', values: { showBorders: true, showCountryNames: false, showFlags: false } },
      { name: 'hard', label: 'Hard', values: { showBorders: false, showCountryNames: false, showFlags: false } },
    ],
    columnMappings: {
      answer: 'name',
      label: 'name',
      latitude: 'latitude',
      longitude: 'longitude',
      group: 'group',
    },
    dataPath: '/data/borders/world-borders.csv',
    dataFilter: [
      { column: 'is_sovereign', values: ['true'] },
      { column: 'group', values: ['North America', 'Central America', 'Caribbean'] },
    ],
    supportingDataPaths: ['/data/borders/world-borders.csv'],
  },
  {
    id: 'geo-countries-south-america',
    title: 'South American Countries',
    description: 'Name the countries of South America from their shape on the map.',
    path: ['Geography', 'Countries'],
    visualizationType: 'map',
    initialViewBox: { x: -85, y: -15, width: 55, height: 72 },
    availableModes: ['free-recall-unordered', 'identify', 'locate', 'prompted-recall'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showFlags', label: 'Flags', defaultValue: false, group: 'display', hiddenBehavior: { hintAfter: 2 } },
    ],
    presets: [
      { name: 'easy', label: 'Easy', values: { showBorders: true, showCountryNames: true, showFlags: true } },
      { name: 'medium', label: 'Medium', values: { showBorders: true, showCountryNames: false, showFlags: false } },
      { name: 'hard', label: 'Hard', values: { showBorders: false, showCountryNames: false, showFlags: false } },
    ],
    columnMappings: {
      answer: 'name',
      label: 'name',
      latitude: 'latitude',
      longitude: 'longitude',
      group: 'group',
    },
    dataPath: '/data/borders/world-borders.csv',
    dataFilter: [
      { column: 'is_sovereign', values: ['true'] },
      { column: 'group', values: ['South America'] },
    ],
    supportingDataPaths: ['/data/borders/world-borders.csv'],
  },
  {
    id: 'geo-countries-oceania',
    title: 'Oceanian Countries',
    description: 'Name the countries of Oceania from their shape on the map.',
    path: ['Geography', 'Countries'],
    visualizationType: 'map',
    initialViewBox: { x: 110, y: 0, width: 70, height: 48 },
    availableModes: ['free-recall-unordered', 'identify', 'locate', 'prompted-recall'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showFlags', label: 'Flags', defaultValue: false, group: 'display', hiddenBehavior: { hintAfter: 2 } },
    ],
    presets: [
      { name: 'easy', label: 'Easy', values: { showBorders: true, showCountryNames: true, showFlags: true } },
      { name: 'medium', label: 'Medium', values: { showBorders: true, showCountryNames: false, showFlags: false } },
      { name: 'hard', label: 'Hard', values: { showBorders: false, showCountryNames: false, showFlags: false } },
    ],
    columnMappings: {
      answer: 'name',
      label: 'name',
      latitude: 'latitude',
      longitude: 'longitude',
      group: 'group',
    },
    dataPath: '/data/borders/world-borders.csv',
    dataFilter: [
      { column: 'is_sovereign', values: ['true'] },
      { column: 'region', values: ['Oceania'] },
    ],
    supportingDataPaths: ['/data/borders/world-borders.csv'],
  },
  {
    id: 'geo-countries-world',
    title: 'Countries of the World',
    description: 'Name all 197 countries of the world from their shape on the map.',
    path: ['Geography', 'Countries'],
    visualizationType: 'map',
    availableModes: ['free-recall-unordered', 'identify', 'locate'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showBorders', label: 'Country borders', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showFlags', label: 'Flags', defaultValue: false, group: 'display', hiddenBehavior: { hintAfter: 2 } },
    ],
    presets: [
      { name: 'easy', label: 'Easy', values: { showBorders: true, showCountryNames: true, showFlags: true } },
      { name: 'medium', label: 'Medium', values: { showBorders: true, showCountryNames: false, showFlags: false } },
      { name: 'hard', label: 'Hard', values: { showBorders: false, showCountryNames: false, showFlags: false } },
    ],
    columnMappings: {
      answer: 'name',
      label: 'name',
      latitude: 'latitude',
      longitude: 'longitude',
      group: 'region',
    },
    dataPath: '/data/borders/world-borders.csv',
    dataFilter: { column: 'is_sovereign', values: ['true'] },
    supportingDataPaths: ['/data/borders/world-borders.csv'],
  },
  {
    id: 'geo-flags-europe',
    title: 'European Flags',
    description: 'Match European countries to their flags.',
    path: ['Geography', 'Flags'],
    visualizationType: 'grid',
    availableModes: ['identify', 'free-recall-unordered'],
    defaultMode: 'identify',
    toggles: [
      { key: 'showCountryNames', label: 'Country names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
    ],
    presets: [],
    columnMappings: {
      answer: 'country',
      label: 'country',
      group: 'region',
    },
    dataPath: '/data/geography/flags/europe.csv',
    supportingDataPaths: [],
  },
  {
    id: 'sci-periodic-table',
    title: 'Periodic Table',
    description: 'Name the elements of the periodic table.',
    path: ['Science', 'Chemistry', 'Periodic Table'],
    visualizationType: 'grid',
    availableModes: ['free-recall-unordered', 'identify'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showSymbols', label: 'Element symbols', defaultValue: true, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showAtomicNumbers', label: 'Atomic numbers', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
    ],
    presets: [
      {
        name: 'easy',
        label: 'Easy',
        values: { showSymbols: true, showAtomicNumbers: true },
      },
      {
        name: 'hard',
        label: 'Hard',
        values: { showSymbols: false, showAtomicNumbers: false },
      },
    ],
    columnMappings: {
      answer: 'name',
      label: 'symbol',
      group: 'category',
    },
    dataPath: '/data/science/chemistry/periodic-table.csv',
    supportingDataPaths: [],
  },
  {
    id: 'sci-element-symbols',
    title: 'Element Symbols',
    description: 'Match chemical elements to their symbols.',
    path: ['Science', 'Chemistry', 'Element Symbols'],
    visualizationType: 'grid',
    availableModes: ['free-recall-unordered', 'identify'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showNames', label: 'Element names', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
    ],
    presets: [],
    columnMappings: {
      answer: 'symbol',
      label: 'name',
      group: 'category',
    },
    dataPath: '/data/science/chemistry/periodic-table.csv',
    supportingDataPaths: [],
  },
  {
    id: 'sci-human-bones',
    title: 'Human Bones',
    description: 'Name the bones of the human skeleton.',
    path: ['Science', 'Biology', 'Human Bones'],
    visualizationType: 'grid',
    availableModes: ['free-recall-unordered', 'identify'],
    defaultMode: 'free-recall-unordered',
    toggles: [],
    presets: [],
    columnMappings: {
      answer: 'bone',
      label: 'bone',
      group: 'region',
    },
    dataPath: '/data/science/biology/human-bones.csv',
    supportingDataPaths: [],
  },
  {
    id: 'hist-emperors-roman',
    title: 'Roman Emperors',
    description: 'Name the emperors of Rome in chronological order.',
    path: ['History', 'Ancient', 'Roman Emperors'],
    visualizationType: 'timeline',
    availableModes: ['free-recall-unordered'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showDates', label: 'Reign dates', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
      { key: 'showDynasty', label: 'Dynasty colours', defaultValue: true, group: 'display', hiddenBehavior: 'never' },
    ],
    presets: [],
    columnMappings: {
      answer: 'emperor',
      label: 'emperor',
      group: 'dynasty',
    },
    dataPath: '/data/history/ancient/roman-emperors.csv',
    supportingDataPaths: [],
  },
  {
    id: 'hist-timeline-ww2',
    title: 'World War II Timeline',
    description: 'Place key events of World War II on a timeline.',
    path: ['History', 'Modern', 'World War II Timeline'],
    visualizationType: 'timeline',
    availableModes: ['free-recall-unordered', 'locate'],
    defaultMode: 'free-recall-unordered',
    toggles: [
      { key: 'showDates', label: 'Event dates', defaultValue: false, group: 'display', hiddenBehavior: 'on-reveal' },
    ],
    presets: [],
    columnMappings: {
      answer: 'event',
      label: 'event',
      group: 'theatre',
    },
    dataPath: '/data/history/modern/ww2-timeline.csv',
    supportingDataPaths: [],
  },
];
